README.md

Josh contributor

---

README.md

Added Contributor Riker Evans to README

added Contributor to README

---

README.md
app.py

Added travel randomizer endpoint and readme instructions

Keatonhall2 branch

---

app.py

Changed output of Travel endpoint to Json

Changed endpoint to json output format

---

README.md
app.py

added subtract, cleaning up

---

README.md
app.py

Also made changes to the calc README and added instructions on how to add matplotlib

added multiply and divide to calc

---

README.md
app.py

Added more dad jokes and updated endpoint readme

Added more dad jokes

---

app.py

fixed syntax bois, cleaned up some code, removed __main__s because not needed for this. Every endpoint but color (dont wanna test tbh) working and app.py runs so we can continue

fixing pls

---

README.md
app.py

added a fact to the random fact endpoint. Changed some formating in the Readme file to keep things consistent.

Changes to Readme and App.py for rebase assignment. 

---

README.md
app.py

Still trying to preform a proper rebase. Will I ever be released from this cycle

added comment to app.py and short tutorial on how to use rebase. 

---

app.py
test/test_travel.py

Move travel endpoint to main app (again I guess, should've made a new branch) and created test_travel.py

---

README.md
app.py
test/test_travel.py

Added test instructions in readme, added flight time in /travel endpoint, added test to see if flight time correctly outputs.

Changed README, app.py, test_travel.py

---

README.md
app.py
test/test_calc.py

for assignment "add more test to the API"

added more tests for calc

---

README.md

Changed Formating of Readme to put all resources related to makeing and running endpoints at the top for easier access
Changed some header for motivation endppoint to follow the same format as the other endpoints.

README changes 

---

README.md
test/test_quotes.py

Add test quotes

---

requirements.txt
test/test_travel.py
test/test_weather.py

Disabled weather test, removed pytest creation from my tests, added requests to requirements.txt

Disabled weather test, removed pytest from tests

---

README.md
app.py
endpoints/brainrot.py
endpoints/dadjoke.py
endpoints/motivation.py
templates/dadjoke.html
test/test_brainrot.py
test/test_dadjoke.py
test/test_motivation.py

Commented out import requests on line 7 in app.py because it kept the app from running
Moved dadjoke endpoints from app.py to their own files inside of new endpoints folder. Confirmed flask app works after changes
Created html file for dadjoke to change the formating of dadjoke endpoints webpage
Updated brainrots html to make the website look more apealing.
Rewrote/added tests to test for the reformated outputs for both brainrot and dadjoke.
Moved the motivation endpoint to its own file in endpoints folder. imported it into app.py app create function.
Created tests for motivation endpoint
Added an about us Section to README and added some details about myself

Sorens api 6 changes

---

README.md
app.py
endpoints/calc.py
endpoints/dadjoke.py
test/test_calc.py

Moved calc endpoint to a bp after adding mod for modulus
Added test for mod
Reformatted part of readme
Fixed Dadjoke endpoint for escape characters

moved calc to endpoint, added mod, fixed dad joke

---

README.md
app.py
requirements.txt
test/test_animal.py

Trav update6

---

Dockerfile
README.md
app.py
requirements.txt

I also removed a duplicate "about me" for Soren in the readme. We don't need to hear about him twice.

Moved WEATHER_API_KEY to .env, added reference in Dockerfile resolves #145

---

.github/workflows/check-app-runs.yml
.github/workflows/run-tests.yml
Dockerfile

feat(dock-test): add workflowboi

---

app.py
templates/weather.html

Changed app.py and weather.html

feat(): /weather now changes color based on temp

---

test/test_weather.py

fix(): Added color testing to test_weather

---

README.md
endpoints/math.py
templates/calc.html
test/test_calc.py

* Added Exponent operator; 'exp'
* Added needed calc.html, calc.js, and readme changes

feat(calc): add 'exp' operation

---

endpoints/math.py
test/test_calc.py

added some sanitation to the /calc and adjusted test for it

feat(api): added some input sanitation to /calc endpoint

---

app.py
templates/index.html
templates/xkcd_comic.html
test/test_xkcd.py

feat(): added xkdc comic endpoint in app.py, added test_xkdc.py file,

---

.idea/.gitignore
.idea/class-api-IT4200-2024-fall.iml
.idea/modules.xml
.idea/vcs.xml
templates/index.html
test/test_allfacts.py

BREAKING CHANGE: Facts column now leads to fact categories correctly

perf(): updated broken links on index.html

---

.github/workflows/semver.yml
Dockerfile

I REALLY hope this works because idk how to test it

fix(): Retrieves WEATHER_API_KEY from github

---

app.py
endpoints/weather.py

Insert unsettling photo from Soren here

fix(): Created blueprint of /weather

---

endpoints/weather.py
templates/weather.html
test/test_weather.py

/weather has animations based on weather conditions MAJOR changed output significantly

perf(): /weather now has animations

---

Dockerfile
README.md
endpoints/version.py
test/test_version.py

BREAKING CHANGE: current-version gone, changed how docker machine sees version

perf(version): fixed env build, made version fixed

---

README.md
endpoints/restaurants.py
templates/index.html
templates/order.html
test/test_restaurants.py

README and tests
BREAKING CHANGE: users now have to choose a restaurant and items, and can no longer just view a list

perf (): changed restaurants from list to pick and choose menu, updated

---

Dockerfile

fix(): added COPY statememt to docker file form images folder.

fix(): added COPY statememt to docker file form images folder.

---

Dockerfile
endpoints/readme.py
test/test_readme.py

feat():
- Changed the output of the readme endpoint to take you directly to the readme instead of a link to the readme.
- Updated unittests

feat(): Minor endpoint change

---

README.md
endpoints/pizza.py
endpoints/soda.py
test/test_pizza.py
test/test_soda.py

added changes to pizza.py and soda.py, also added more tests for the recently added code, and wrote the new features to the readme file.

api week 9

---

static/script.js
static/style.css
templates/index.html

Added a dark mode toggle option for the home page of the api

Added Dark Mode to '/' Endpoint

---

README.md
app.py
endpoints/color_hexifier.py
static/color_hexifier.css
static/color_hexifier.js
templates/color_hexifier.html
test/test_color_hexifier.py

Added color_hexifier.js and color_hexifier.css in the static directory.
Added color_hexifier.py in the endpoints directory.
Updated the tests_color_hexifier.py file.
Updated the README.md

Added a UI to Color Hexifier

---

app.py
test/test_multiply.py
test/test_travel.py

feat(): added to the travel and fixed some multiply minor change

---

app.py
dynamo/seed.bash

- Implemented a new endpoint `/items` in the API to retrieve data from the DynamoDB table.
- Modified `seed.bash` to create and seed data into the `items` table for testing.

feat(): added /items endpoint to fetch data from DynamoDB

---

dynamo/seed.bash
endpoints/fortune.py

feat(): Modified fortune.py and seed.bash

---

Dockerfile

Edited Dockerfile to Expose port 5001 instead of 5000.

fix(Dockerfile): Changed exposed port in Dockerfile to be 5001

---

README.md
test/puppeteer_test_calc.js

Working..... for now 
See Here if x to doubt:
https://mediaspace.utahtech.edu/media/Puppeteerwork/1_26rnvsmw

fix(calc): add puppeteer file?

---

test/test_mock_and_stub.py

adding my tests for Improved Testing assignment

feat(): adding testing for mock and stub

---

test/test_photogallery.py

fix(): Added Tests that Check for proper Permissions on files in the images folder.

fix(): Improving photo gallery Tests

---

endpoints/weather.py
templates/index.html
templates/weather.html
test/test_weather.py

MAJOR: User input for /weather has changed, now input is through text box rather than URL
Added user input box for /weather (now requires redirects)
Modified subsequent tests for new input box
Modified weather.html to properly accommodate error handling from invalid input
Modified index.html to correctly redirect to /weather endpoint

perf(): Added user input and test to /weather
